### ISSUE TITLE
Demo site JSON output

### ISSUE THREAD

**Issue by WubbleWobble** [api-platform/demo#143]
**API Platform version(s) affected**: 1.0.0

**Description**  

I've been looking at the demo site deployed at https://demo.api-platform.com/

I noticed that on the GET /books endpoint whilst the [JSON-LD output](https://demo.api-platform.com/books.jsonld?page=1) returns identifiers as "@ id", the [plain JSON output](https://demo.api-platform.com/books.json?page=1) doesn't look to return any IDs whatsoever.

It therefore seems as if impossible to actually use the plain JSON format endpoints as I'd have no IDs to pass to other endpoints?

This may be a configuration bug or possibly I'm missing something! :)

**Comment by vincentchalamon** [comment]
Hi @WubbleWobble,

This is the configuration we wanted to expose on this project (api-platform/demo). If you need any link to a resource, you should use JSON-LD (**_Linked_** Data :wink:).

If you really need to expose the database identifier whatever format is requested, just add the serialization group to the related property:

```php
class Book
{
    // ...
    /**
     * ...
     * @Groups("book:read")
     */
    private $id;
```

Hope it answers your question :-)

**Comment by WubbleWobble** [comment]
Thanks for the reply :)

It somewhat answers it. I guess my confusion comes from the expectation that different clients could request different formats to suit their preferences and all representations would be equally usable.

A JSON API would however be useless if IDs are omitted. I couldn't say PATCH one of the records because I wouldn't know its ID. RESTful JSON APIs were used for quite a while before JSON-LD was created, after all.

On the other hand, I could specifically turn on IDs on with the Groups annotation as above, and the JSON format would then be usable, but the JSON-LD format would end up with an unneeded "id" field - not the end of the world I know, but annoying :)

**Comment by vincentchalamon** [comment]
I think it depends on the use case. In the current project, we prefer using JSON-LD as we take advantage of the resource iri, instead of building it manually with the database id and guessing the right iri...

On another scenario, it would be possible to call the API in plain JSON, for example in read-only just to expose some data. But as I said, it depends on the scenario.

In this case, it could be related to #17 to add a scenario to consume the API in plain JSON. If so, don't hesitate to open a PR to add a custom scenario to illustrate your use-case.

**Comment by vincentchalamon** [comment]
@WubbleWobble Is this issue solved? Do our previous conversation answered your question?

**Comment by WubbleWobble** [comment]
Honestly I appreciate the replies but still feel like we're having two slightly different conversations. I'll try to explain.

I point out that the JSON endpoints don't return IDs, and you tell me that's what JSON-LD's for. But JSON API endpoints would generally return IDs to be useful - after all, without IDs you can't PATCH/DELETE/GET specific records. My understanding is that the LD in JSON-LD refers to being able to find other related endpoints (e.g. you've asked to GET a book? Well - here's another endpoint that you can use to create a new book. You've asked to GET for a page of books? Well - here's how to get the previous/next pages).

You explain how to force IDs on by setting the normalisation context - and that's a good workaround - but whilst it makes the JSON interface useful, it introduces a redundant ID into the JSON-LD output.

I too would use the JSON-LD format - but for me the whole point of formats is that I'd turn them on, and presto - this API supports both JSON and JSON-LD clients simultaneously (as opposed to either turning on IDs and just supporting JSON, or not turning them on and just supporting only JSON-LD). Another related question is "What use is a JSON API which doesn't provide IDs? What could it be used for?"

I guess one analogy would something like having a tourist information office that caters for both English and French. I'd expect to get the same minimal and correct response not matter which language I spoke. (Rather than say the attendant omitting landmark coordinates if you spoke French, or the giving you landmark coordinates twice in slightly different ways if you spoke English :D)

Anyway - I'm very appreciative of the replies and thank you for putting up with my rambling replies. Happy for you to close the issue as I think it's probably more aimed at API Platform itself rather than the demo site, but you happened to have a working example that I could point at and say "why is this?" :)
