### ISSUE TITLE
Swagger Documentation Microsoft Edge 41.16299.1480.0 it wants to download it instead of display 

### ISSUE THREAD

**Issue by worthwhileindustries** [api-platform/demo#144]
**API Platform version(s) affected**: demo site https://demo.api-platform.com/

**Description**  

![image](https://user-images.githubusercontent.com/3536254/73030349-a6ecb000-3df6-11ea-8a82-9769d45dce04.png)
**How to reproduce**  

navigate using Edge or IE https://demo.api-platform.com/ (not the new chromium edge)
**Possible Solution**  

**Additional Context**

**Comment by worthwhileindustries** [comment]
bump ^^^

**Comment by soyuka** [comment]
We can not reproduce this issue, can someone debug with edge ? Maybe an issue with our Content-Type ?

**Comment by soyuka** [comment]
Tracked to : https://github.com/willdurand/Negotiation/issues/98

**Comment by soyuka** [comment]
We will tag this as a wontfix in Api Platform and hope that microsoft fixes its browser :/.
