### ISSUE TITLE
How to configure only scheme https in link response header

### ISSUE THREAD

**Issue by ppailleaud** [api-platform/demo#157]
Hello guys, 

In my application, the link response header is only in Http. Which poses a mixed content problem. I want to use Https scheme

At what level to position this configuration (Nginx, Symfony, Api-Platform). Do you have an example ? 

Thinks by advance for your help

![image](https://user-images.githubusercontent.com/25134807/93200501-1e899980-f750-11ea-8c4e-7deb6ff4a911.png)

**Comment by soyuka** [comment]
You need to set up trusted proxy on the API see https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies. The API isn't requested via HTTPS and therefore thinks it's served as HTTP.
