### ISSUE TITLE
Should have a more complex demo

### ISSUE THREAD

**Issue by inf3rno** [api-platform/demo#17]
I think the point loses with this oversimplified demo. It is just a CRUD API, and you map REST resources to ORM entities, which works only if an application has an anaemic domain model. On the other hand this is a great project and should be developed further.

**Comment by dunglas** [comment]
All contributions to the demo are welcome!

**Comment by inf3rno** [comment]
@dunglas 
Sorry, I no longer write PHP, but I'll check the code of your framework. Maybe I can write the nodejs equivalent if you don't mind.

**Comment by mysiar** [comment]
I just start thinking about updating demo with some custom data providers yesterday :)

**Comment by inf3rno** [comment]
@mysiar 
To make it clear what I meant by my first post; by REST you map links to operations, and not HTTP methods to CRUD and resource to entity or entity set. I added some examples as a more detailed explanation.

By CRUD you do something like 
```
GET /books/ <-> bookRepo.readAll()
    GET <-> readAll // CRUD read
    /books/ <-> bookRepo.*() // book repository, whole set
```

```
GET /books/1 <-> bookRepo.readOne(1)
    GET <-> readOne // CRUD read
    /books/1 <-> bookRepo.*(1) // a book entity
```

To make it more complex you can map reduce your collection with some filters:

```
GET /books/?q=php<-> bookRepo.readAllByFilter("php")
    GET <-> readAllByFilter // CRUD read, but not a simple one
    /books/?q=php <-> bookRepo.*("php") // whole set map reduced by filter
```
```
DELETE /books/?old=true <-> bookRepo.removeAllOld()
    DELETE <-> removeAllOld // CRUD remove
    /books/?old=true <-> bookRepo.*() // should be a reduced set, but here we have the whole set, since the removeAllOld method describes the filter, mapping does not seem to work here
```

Or you can use different methods as expected:

```
POST /expense/report/1/approval <-> expenseReportRepo.update(1, {approved: true})
    POST <-> update(*, {approved: true}) // CRUD, but should be create by POST so mapping does not work this time
    /expense/report/1/approval <-> expenseReportRepo.*(1, *) // a resource can have many different URIs, so the mapping still works here
```

Or if we don't want to use anaemic domain model:

```
POST /expense/report/1/approval <-> report = expenseReportRepo.readById(1); report.approve()
    POST <-> report.approve() // not even CRUD like method, mapping does not work
    /expense/report/1/approval <-> expenseReportRepo.*(1) // still ok
```

What if we don't want to save anything on the server?

```
POST /calculator/?q=1+1 <-> results = calculatorService.count("1+1")
    POST <-> calculatorService.count(*) // non-CRUD
    /calculator/?q=1+1 <-> *("1+1") // we don't have an entity, since we don't save anything
```

**Comment by mysiar** [comment]
@inf3rno this what you wrote above is completely different than what I thought :)

**Comment by inf3rno** [comment]
Ofc. generating CRUD is a good and necessary feature, but it does not cover every problem. If we want to dev real REST APIs, not just CRUD APIs, then we should be able to implement these examples somehow using your platform. I did not read the code, maybe there is no need to modify it at all, idk.

**Comment by snoob** [comment]
I don't really know what is the api-platform/demo purpose. On my developer POV, It could be use as a developer reference to accelerate the api creation process even more. Most of very used features are well documented but their integration on demo repository could be a nice addition (ApiOrder, EventSystem (PRE_READ or POST_READ maybe ?) for example) 

Conversely, common use cases can be hard to implement when you are new on api platform. Maybe some cookbook are missing on the documentation ? Or maybe api-platform/demo could be the nice place for this ! Let's see some example :
- New field type on book Entity with predefined values (biography, science fiction, drama, etc...) and documented on swagger thanks to enum. An endpoint to feed the front selectbox (custom endpoint or @ApiRessource not mapped on database ?) should be available also. I don't know what is the best practices on api side.
- How to handle API side translation ? (validation or API error message)
- Some business logic on book or review entity + phpunit unit testing . 5 reviews max per book ?

**Comment by dunglas** [comment]
@snoob I agree it would be nice additions. What would be great is to have both cookbook and code in the demo.

The project is now autodeployed, and all PRs to illustrate more complex use cases are very welcome.

**Comment by Rebolon** [comment]
Hi,
improving the demo with the usage of DataProvider and DataPersister would be interesting. I failed to make it works finely and quickly with Pagination, Sort or Filters. Any tips on this is welcome.
I have a demo project here https://github.com/Rebolon/php-sf-flex-webpack-encore-vuejs/ that try to implement more thing, but it's not perfect and i'm fixing some wrong implementations.

**Comment by COil** [comment]
Hello everyone, we started to add more concrete/complex examples. They are listed in the [REAMDE.md](REAMDE.md) file.
