### ISSUE TITLE
Run demo locally fails: Service 'consumer' failed to build

### ISSUE THREAD

**Issue by andrekutianski** [api-platform/demo#192]
All attempts to run this demo locally do not work, when running the docker-compose always fails in the step below

(...)
```
Step 28/36 : RUN set -eux; 	mkdir -p var/cache var/log; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync
 ---> Running in 7c9b0eb0fd97
+ mkdir -p var/cache var/log
+ composer dump-autoload --classmap-authoritative --no-dev
Generating optimized autoload files (authoritative)
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
Generated optimized autoload files (authoritative) containing 4776 classes
+ composer run-script --no-dev post-install-cmd

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
Executing script security-checker security:check [KO]
 [KO]
Script security-checker security:check returned with error code 1
!!                                                              
!!    The web service failed for an unknown reason (HTTP 403).  
!!                                                              
!!  
Script @auto-scripts was called via post-install-cmd
ERROR: Service 'consumer' failed to build: The command '/bin/sh -c set -eux; 	mkdir -p var/cache var/log; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync' returned a non-zero code: 1

```

**Comment by thomasrolle** [comment]
Are you using sensiolabs/security-checker?

The service stopped some days ago:

https://packagist.org/packages/sensiolabs/security-checker

**Comment by naobodson** [comment]
Hello ! 
I have the same issue.

```
Executing script cache:clear [OK]
Executing script assets:install public [OK]
Executing script security-checker security:check [KO]
 [KO]
Script security-checker security:check returned with error code 1
!!
!!    The web service failed for an unknown reason (HTTP 403).
!!
!!
Script @auto-scripts was called via post-install-cmd
ERROR: Service 'consumer' failed to build : The command '/bin/sh -c set -eux;   mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative --no-dev;       composer run-script --no-dev post-install-cmd;  chmod +x bin/console; sync' returned a non-zero code: 1
```

what do we have to do to remove security-checker and replace it ?

**Comment by simocheccoli** [comment]
Hi!
Same issue here.


```
 > [quay.io/api-platform/php:latest api_platform_php 21/25] RUN set -eux;       mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative --no-dev;       composer run-script --no-dev post-install-cmd;  chmod +x bin/console; sync:
#35 0.316 + mkdir -p var/cache var/log
#35 0.316 + composer dump-autoload --classmap-authoritative --no-dev
#35 0.567 Generating optimized autoload files (authoritative)
#35 1.869 composer/package-versions-deprecated: Generating version class...
#35 1.871 composer/package-versions-deprecated: ...done generating version class
#35 1.874 Generated optimized autoload files (authoritative) containing 4723 classes
#35 1.885 + composer run-script --no-dev post-install-cmd
#35 2.077 
#35 2.077 Run composer recipes at any time to see the status of your Symfony recipes.
#35 2.077 
#35 2.086 Executing script cache:clear [OK]
#35 3.733 Executing script assets:install public [OK]
#35 4.014 Executing script security-checker security:check [KO]
#35 4.367  [KO]
#35 4.367 Script security-checker security:check returned with error code 1
#35 4.367 !!                                                              
#35 4.367 !!    The web service failed for an unknown reason (HTTP 403).  
#35 4.367 !!                                                              
#35 4.367 !!  
#35 4.367 Script @auto-scripts was called via post-install-cmd
----
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -eux;         mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative --no-dev;       composer run-script --no-dev post-install-cmd;  chmod +x bin/console; sync]: exit code: 1

```

**Comment by matrizlab** [comment]
Hi there
same issue for me too

`Removing intermediate container 734c30d37545
 ---> e3be81d977ee
Step 20/36 : COPY .env ./
 ---> 96ee10174778
Step 21/36 : RUN composer dump-env prod
 ---> Running in 56d627703b37
Successfully dumped .env files in .env.local.php
Removing intermediate container 56d627703b37
 ---> 2582d900fd47
Step 22/36 : COPY bin bin/
 ---> b9a29f77544a
Step 23/36 : COPY config config/
 ---> 35dddc0527aa
Step 24/36 : COPY data data/
 ---> cb8819236fc2
Step 25/36 : COPY public public/
 ---> 6deb58fa8e42
Step 26/36 : COPY src src/
 ---> 060ae0429ef4
Step 27/36 : COPY fixtures fixtures/
 ---> 4452846b7aa4
Step 28/36 : RUN set -eux; 	mkdir -p var/cache var/log; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync
 ---> Running in 7721a2f6ae0a
+ mkdir -p var/cache var/log
+ composer dump-autoload --classmap-authoritative --no-dev
Generating optimized autoload files (authoritative)
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
Generated optimized autoload files (authoritative) containing 4723 classes
+ composer run-script --no-dev post-install-cmd

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
Executing script security-checker security:check [KO]
 [KO]
Script security-checker security:check returned with error code 1
!!                                                              
!!    The web service failed for an unknown reason (HTTP 403).  
!!                                                              
!!  
Script @auto-scripts was called via post-install-cmd
ERROR: Service 'consumer' failed to build: The command '/bin/sh -c set -eux; 	mkdir -p var/cache var/log; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync' returned a non-zero code: 1
`
