### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by fzaninotto** [api-platform/demo#222]
**API Platform version(s) affected**: ??? ( I cloned the master branch)

**Description**  

Calling the load-fixtures command fails

![image](https://user-images.githubusercontent.com/99944/128051878-691aec2c-0e60-4fa9-8483-202e8899a263.png)

**How to reproduce**  

- clone this repo
- follow the install instructions

**Comment by vincentchalamon** [comment]
Hi @fzaninotto,

Thanks for the bug report. The fixtures are automatically loaded on local using the docker entrypoint: https://github.com/api-platform/demo/blob/main/api/docker/php/docker-entrypoint.sh#L65

I've opened a PR to fix the install instructions.
