### ISSUE TITLE
Improve "Install"-section in README.md

### ISSUE THREAD

**Issue by Chris53897** [api-platform/demo#228]
Hi.
If you just follow the instruction in the [Install-Section in README.md](https://github.com/api-platform/demo#install) you will get the error.
`yaml: line 53: did not find expected tag URI`

The problem is the first "!" in each line. So you have to change that.
MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}

I would suggest
a) Add the info to the install-section
b) just set a valid default password so the demo works out of the box (security needs to be considered, but it should be overwritten by docker-compose.prod.yml for production)

**Comment by rowanparker** [comment]
I think that error is not related to a bad yaml file, but rather that there is an outstanding bug with the latest version of docker-compose.

https://github.com/docker/compose-cli/issues/2028

**Comment by Chris53897** [comment]
@rowanparker Thanks. v2 has a lot of bugs ;(
