### ISSUE TITLE
How to add more filter input to Toopbook

### ISSUE THREAD

**Issue by lchhieu** [api-platform/demo#321]
I want to add more input fields into swagger for filter. So How to do that ?

**Comment by vincentchalamon** [comment]
Hi,

If you wanna contribute to this project, please open a Pull Request. However, the goal of TopBook here is just to demonstrate how to use a custom provider without too much complexity.

Anyway, if you're just looking for a way to declare filters and extend the Swagger documentation, I recommend you to have a look at the documentation: https://api-platform.com/docs/.
