### ISSUE TITLE
Docker compose failed to up

### ISSUE THREAD

**Issue by itxiaoma-cn** [api-platform/demo#326]
Building pwa
ERROR: Dockerfile parse error line 23: Unknown flag: link

docker version
Version:           19.03.5

**Comment by vincentchalamon** [comment]
Hi @itxiaoma-cn,
Could you provide more information: environment, OS, command executed, etc.

**Comment by vincentchalamon** [comment]
Closing as inactive. Feel free to comment again if you still have the issue, and provide as much information as possible.
