### ISSUE TITLE
Unable to login in Admin section, ssl certificate issues

### ISSUE THREAD

**Issue by alcidesrh** [api-platform/demo#339]
**API Platform version(s) affected**: 3.2

 Click Admin section from https://localhots got this:

<img src="https://github.com/api-platform/demo/assets/29238564/33fc32d8-43ab-47ca-ba28-89a1a13057a4" width="350">

*With docker compose logs -f the output*:  

error: {
demo-pwa-1 | message: 'write EPROTO 586BFF4A977F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80\n',
demo-pwa-1 | stack: 'Error: write EPROTO 586BFF4A977F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80\n' +
demo-pwa-1 |       '\n' +
demo-pwa-1 |       '    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)',
demo-pwa-1 |     name: 'Error'
demo-pwa-1 |   },
demo-pwa-1 |   providerId: 'keycloak',
demo-pwa-1 |   message: 'write EPROTO 586BFF4A977F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80\n
demo-pwa-1 | }`

<img src="https://github.com/api-platform/demo/assets/29238564/d56c163b-09a4-4ca9-ac5c-0be325b6f867 " width="100%">

**Comment by vincentchalamon** [comment]
Hi,
This is due to `keycloak-config-cli` not able to load the configuration file on the Keycloak instance. This bug has been reported on https://github.com/bitnami/containers/issues/51267, investigation in progress.
