### ISSUE TITLE
Error to login in admin's dashboard.

### ISSUE THREAD

**Issue by alcidesrh** [api-platform/demo#372]
**API Platform version(s) affected**: x.y.z

**Description**  
Just can't login into admin's dashboard.

![Screenshot_20240121_171649](https://github.com/api-platform/demo/assets/29238564/7027cba2-a1ef-469f-8dfb-58e135d38b46)

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by vincentchalamon** [comment]
Hello @alcidesrh
A PR has just been merged fixing this issue. It will be deployed on production on the next release.

**Comment by vincentchalamon** [comment]
Fixed and deployed in 3.2.12
