### ISSUE TITLE
Quote pls.

### ISSUE THREAD

**Issue by S33G** [api-platform/demo#377]
**API Platform version(s) affected**: 
N/A

**Description**  
Unquoted booleans in docker-compose.yml can cause problem

**How to reproduce**  
When working with tools such as ansible, the yml parser assumes the following is being adhered to.

See here:
https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
> YAML boolean values ("true", "false", "yes", "no", "on", "off") must be enclosed in quotes, so that the parser interprets them as strings.

**Possible Solution**  
Quote the booleans so it's inline with docker's reccomendations

**Comment by vincentchalamon** [comment]
Hi @S33G,

Thanks for the tip. I've only found `KEYCLOAK_AVAILABILITYCHECK_ENABLED` boolean environment variable in `compose.override.yaml` file which doesn't have quotes. Did you notice other environment variables which require to be quoted?
