### ISSUE TITLE
Load FixturesBundle on require instead of require-dev

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/demo#79]
Fixtures are loaded on production, so why require them on dev only? It impacts the deploy process by forcing the use of the following script:
```
APP_ENV=dev composer install -n && bin/console d:m:m --no-interaction --env=prod && bin/console d:s:u --force --env=prod && bin/console hautelook:fixtures:load -n --env=dev && APP_ENV=prod composer --no-dev install --classmap-authoritative && echo deployed
```
This could be improved by loading the FixturesBundle on require and execute the fixtures:load command directly on production.

**Comment by vincentchalamon** [comment]
Load fixtures through a k8s job? (cf. @pborreli)

**Comment by dunglas** [comment]
It's a edge case for our deployment of the demo. For a real app, fixtures shouldn't be used in prod (you'll use real data). I prefer to have a hack in the deployment script than promoting a bad practice: the main goal of this repository is to teach how to create more advanced API Platform apps.
