### ISSUE TITLE
Fix admin build

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/demo#80]
>Module not found: Can't resolve 'rdf-canonize-native' in '/home/travis/build/api-platform/demo/admin/node_modules/rdf-canonize/lib'

**Comment by dunglas** [comment]
See https://github.com/api-platform/api-platform/commit/8b846dc2c23edb428d69919780140927b8b1bd2b

**Comment by vincentchalamon** [comment]
@dunglas [Already done](https://github.com/api-platform/demo/blob/master/admin/Dockerfile), but the problem is still here

**Comment by dunglas** [comment]
Actually it's not a real issue, because `rdf-canonize` is only executed in the browser, so it will not benefit from the native Node implementation, but it would be nice to get read of this error.
